In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.3'

In [3]:
np.array([2,3,4,5])

array([2, 3, 4, 5])

In [4]:
np.array([3,4,5.4], dtype = "float32")

array([3. , 4. , 5.4], dtype=float32)

In [8]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
np.zeros(10, dtype = "float")

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones((3,4), dtype = "int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [11]:
np.full((3,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [13]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.random.random((3,3))

array([[0.16129748, 0.83938581, 0.35336774],
       [0.53414065, 0.97959123, 0.60560249],
       [0.51478092, 0.51007217, 0.9232388 ]])

In [17]:
np.random.normal(0,1,(3,3))

array([[ 0.6579384 ,  1.2124798 , -1.09910572],
       [-1.88149456,  0.62743522,  0.68799538],
       [-1.96464647, -0.42186196,  0.10249851]])

In [18]:
np.random.randint(0,10, (3,3))

array([[2, 2, 4],
       [8, 2, 4],
       [4, 9, 6]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.empty(3)

array([1., 1., 1.])

In [21]:
x1 = np.random.random(3)

In [22]:
x2 = np.random.normal(0,1,(3,3))

In [23]:
x3 = np.random.randint(1,20, (2,3,4))

In [24]:
print(x1)
print(x2)
print(x3)

[0.39046549 0.54633391 0.22818767]
[[ 0.62791031 -0.02181816 -0.04982786]
 [ 0.45699737 -1.19177916  0.46493451]
 [ 0.13284575  0.58082191  1.10534369]]
[[[ 1 13 10 15]
  [15  3  3 13]
  [ 8 19  6  8]]

 [[10  4  6 13]
  [ 2  3 18  1]
  [19  8  5  1]]]


In [27]:
print(x3.ndim)
print(x3.shape)
print(x3.size)
print(x3.itemsize)
print(x3.nbytes)

3
(2, 3, 4)
24
8
192


In [28]:
x1[0]

0.3904654886443023

In [29]:
x1[-1]

0.22818766928376943

In [30]:
x1[-2]

0.5463339075678048

In [31]:
x2[2,2]

1.105343689051635

In [32]:
x2[0,-1]

-0.04982785727104415