In [1]:
import numpy as np

In [2]:
a = np.array((3,2), dtype = "int")

In [3]:
a

array([3, 2])

In [4]:
b = np.random.randint(6, size = (3,2))

In [5]:
b

array([[4, 2],
       [4, 0],
       [0, 4]])

In [7]:
print(b.ndim, "\n", b.shape, "\n", b.size)

2 
 (3, 2) 
 6


In [8]:
x = np.arange(12).reshape(4,3)

In [9]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
np.split(x, (1,2)) #<- 1st row, 2nd row

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [12]:
y = np.arange(20)

In [13]:
np.split(y, (3,8,15))

[array([0, 1, 2]),
 array([3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [15]:
np.vsplit(x, 2)

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [17]:
np.hsplit(x, 3)

[array([[0],
        [3],
        [6],
        [9]]), array([[ 1],
        [ 4],
        [ 7],
        [10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [ ]:
# np.abs(), np.absolute(), np.sin(), np.exp(), np.power(), np.log2(), np.log(), np.log10()

In [ ]:
# np.add.reduce(), np.multiply.reduce(), np.add.accumulate(), np.sum(), np.max(), np.min()
# np.prod(), np.any(), np.all(), np.std(), np.var(), np.argmin(), np.argmax()

In [19]:
# np.equal(), np.not_equal()
# np.less(), np.greater(), less_equal(), greater_equal()
np.sum(x > 2), #np.count_zero(x <6)
# np.sort(), np.argsort()

(9,)

In [20]:
# sort rowwise, columnwise, flattened
a = np.array([[10,40],[30,20]])
np.sort(a, axis = 0)

array([[10, 20],
       [30, 40]])

In [21]:
np.sort(a, axis = 1)

array([[10, 40],
       [20, 30]])

In [22]:
np.sort(a, axis = None)

array([10, 20, 30, 40])

In [23]:
# Write a NumPy program to create a structured array from given student name, height, 
# class and their data types. Now sort the array on height.

data_type = [("name", "S15"), ("class", int), ("height", float)]
students = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]

a = np.array(students, dtype = data_type)

In [24]:
a

array([(b'James', 5, 48.5 ), (b'Nail', 6, 52.5 ), (b'Paul', 5, 42.1 ),
       (b'Pit', 5, 40.11)],
      dtype=[('name', 'S15'), ('class', '<i8'), ('height', '<f8')])

In [25]:
np.sort(a, order = "height")

array([(b'Pit', 5, 40.11), (b'Paul', 5, 42.1 ), (b'James', 5, 48.5 ),
       (b'Nail', 6, 52.5 )],
      dtype=[('name', 'S15'), ('class', '<i8'), ('height', '<f8')])

In [ ]:
# np.lexsort() - returns indices
# np.partition(nums, 4), np.argpartition(x, 4)